### ISSUE TITLE
Diagrama de sequência

### ISSUE THREAD

**Issue by SannyaArvelos** [track-cooler/app_track_cooler#4]
O Diagrama de sequência deverá representar a sequência de processos, mostrando a sequência do comportamento do aplicativo.

**Comment by byronkamal** [comment]
**Diagramas feitos, imagens logo abaixo**

**Comment by byronkamal** [comment]
![image](https://user-images.githubusercontent.com/18502121/94976920-e5417f80-04ec-11eb-938c-63719239ab45.png)
![image](https://user-images.githubusercontent.com/18502121/94976928-f38f9b80-04ec-11eb-838a-ee5c128e9111.png)
![image](https://user-images.githubusercontent.com/18502121/94976941-fc806d00-04ec-11eb-8a33-62329fb27140.png)
![image](https://user-images.githubusercontent.com/18502121/94976945-0013f400-04ed-11eb-8882-cdebbcdd855b.png)
