### ISSUE TITLE
[TS] API para emular dados

### ISSUE THREAD

**Issue by SannyaArvelos** [track-cooler/app_track_cooler#45]
**Descrição**

Desenvolver API, para poder emular os dados necessários para funcionamento do aplicativo do Track Cooler.

Ao longo da sprint, as tasks necessárias para o desenvolvimento serão acrescentadas aqui de acordo com a demanda.

**Comment by byronkamal** [comment]
**O que falta:**
- [x] Conectar bluetooth com cooler (lista de disponiveis)
- [x] Receber o modo "Seguir bluetooth"
- [x] Receber geoloc
- [x] Escoar agua
